django-twa/src/twa/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns( '',
    # Admin
    ( r'^admin/doc/', include( 'django.contrib.admindocs.urls' ) ),
    #( r'^admin/(.*)', admin.site.root ),
    ( r'^admin/', include(admin.site.urls) ),
    ( r'^i18n/', include( 'django.conf.urls.i18n' ) ),
    #( r'^logout/$', 'django.contrib.auth.views.logout_then_login' ),
    #( r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html'} ),
 )

if settings.DEBUG:
    urlpatterns += patterns( '',
        ( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
     )

urlpatterns += patterns( 'twa.members.views',
#    ( r'^$', 'index' ),
    ( r'^lang/(.*)/$', 'set_lang' ),
    ( r'^$', 'public' ),
    ( r'^antrag/$', 'antrag' ),
    ( r'^antrag/$', 'membership_online_request' ),
    ( r'^associations/$', 'associations' ),
    ( r'^association/(\d+)/$', 'association' ),
    ( r'^document/(.*)/$', 'documents_handler' ),
    ( r'^image/(.*)/(.*)/$', 'image_handler' ),
    ( r'^dojos/$', 'dojos2' ),
    ( r'^dojo/(\d+)/$', 'dojo2' ),
    ( r'^dojos/csv/$', 'dojos_csv' ),
    ( r'^downloads/$', 'downloads' ),
    ( r'^graduations/$', 'graduations2' ),
    ( r'^info/$', 'info' ),
    ( r'^licenses/$', 'licenses' ),
    ( r'^licenses/dojo/(?P<dojo_id>\d+)/$', 'licenses' ),
    ( r'^licenses/twa/$', 'licenses', {'twa_status': True} ),
    ( r'^licenses/notwa/$', 'licenses', {'twa_status': False} ),
    ( r'^license-requests/$', 'license_requests' ),
    ( r'^license-rejected/$', 'license_rejected' ),
    ( r'^licenses/xls/$', 'licenses_xls' ),
    ( r'^license-requests/xls/$', 'license_requests_xls' ),
    ( r'^login/$', 'twa_login' ),
    ( r'^logout/$', 'twa_logout' ),
    ( r'^members/$', 'members2' ),
    ( r'^members/all/$', 'members_all' ),
    ( r'^member/(\d+)/$', 'member2' ),
    ( r'^member-requests/$', 'member_requests' ),
    ( r'^member-requests/dojo/(?P<dojo_id>\d+)/$', 'member_requests' ),
    ( r'^member-requests/region/(?P<region_id>\d+)/$', 'member_requests' ),
    ( r'^member-requests/open/$', 'member_requests', {'status': '1'} ),
    ( r'^member-requests/accepted/$', 'member_requests', {'status': '2'} ),
    ( r'^member-requests/to-be-confirmed/$', 'member_requests', {'status': '6'} ),
    ( r'^member-requests/confirmed/$', 'member_requests', {'status': '5'} ),
    ( r'^member-requests/verify/$', 'member_requests', {'status': '4'} ),
    ( r'^member-requests/member/$', 'member_requests', {'status': '10'} ),
    ( r'^member-requests/nopayment/$', 'member_requests', {'no_payment_filter': True} ),
    ( r'^member-requests/confirmation-email/$', 'confirmation_email' ),
    ( r'^member-requests/accept_open_requests/$', 'accept_open_requests' ),
    ( r'^member-requests/twa-ids/$', 'create_twa_ids' ),
    ( r'^member-requests/xls/$', 'membership_requests_xls' ),
    ( r'^members/csv/$', 'members_csv' ),
    ( r'^members/xls/$', 'members_xls' ),
    ( r'^news/$', 'news_archive' ),
    ( r'^news/(\d+)/$', 'news' ),
    ( r'^news/preview/(\d+)/$', 'news_preview' ),
    ( r'^nominations-xls$', 'nominations_xls' ),
    ( r'^suggestions/$', 'suggestions2' ),
 )

urls.py
#-*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

from twa.members.models import NewsDeFeed, NewsEnFeed, SeminarDeFeed, SeminarEnFeed

admin.autodiscover()

urlpatterns = patterns('',
    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    #( r'^admin/(.*)', admin.site.root ),
    (r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    #( r'^logout/$', 'django.contrib.auth.views.logout_then_login' ),
    #( r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html'} ),
    )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
        )

urlpatterns += patterns('',
        (r'^feed/news-de', NewsDeFeed()),
        (r'^feed/news-en', NewsEnFeed()),
        (r'^feed/seminars', SeminarDeFeed()),
        (r'^feed/seminars-en', SeminarEnFeed()),
    )

urlpatterns += patterns('twa.members.views',
    #    ( r'^$', 'index' ),
    (r'^$', 'public'),
    (r'^association/(\d+)/$', 'association'),
    (r'^associations/$', 'associations'),
    (r'^birthdays/$', 'birthdays'),
    (r'^create-teachers-page/$', 'licensees'),
    (r'^teachers/mailinglist/$', 'licensees_mailinglist'),
    (r'^document/(.*)$', 'documents_handler'),
    (r'^dojo/(\d+)/$', 'dojo'),
    (r'^dojo/(\d+)/csv/$', 'dojo_csv'),
    (r'^dojos/$', 'dojos'),
    (r'^dojos/csv/$', 'dojos_csv'),
    (r'^downloads/$', 'downloads'),
    (r'^exit-to-inactive/$', 'exit_to_inactive'),
    (r'^membership/$', 'downloads'),
    (r'^graduations/$', 'graduations'),
    (r'^image/(.*)/(.*)/$', 'image_handler'),
    (r'^image/(.*)$', 'documents_handler'),
    (r'^info/$', 'info'),
    (r'^license-holders/$', 'licensees'),
    (r'^license-rejected/$', 'license_rejected'),
    (r'^license-requests/$', 'license_requests'),
    (r'^license-requests/xls/$', 'license_requests_xls'),
    (r'^licenses/$', 'licenses'),
    (r'^licenses/dojo/(?P<dojo_id>\d+)/$', 'licenses'),
    (r'^licenses/notwa/$', 'licenses', {'twa_status': False}),
    (r'^licenses/twa/$', 'licenses', {'twa_status': True}),
    (r'^licenses/xls/$', 'licenses_xls'),
    (r'^login/$', 'twa_login'),
    (r'^logout/$', 'twa_logout'),
    (r'^member-requests/$', 'member_requests'),
    (r'^member-requests/accept_open_requests/$', 'accept_open_requests'),
    (r'^member-requests/accepted/$', 'member_requests', {'status': '2'}),
    (r'^member-requests/confirmation-email/$', 'confirmation_email'),
    (r'^member-requests/confirmed/$', 'member_requests', {'status': '5'}),
    (r'^member-requests/dojo/(?P<dojo_id>\d+)/$', 'member_requests'),
    (r'^member-requests/member/$', 'member_requests', {'status': '10'}),
    (r'^member-requests/nopayment/$', 'member_requests', {'no_payment_filter': True}),
    (r'^member-requests/open/$', 'member_requests', {'status': '1'}),
    (r'^member-requests/region/(?P<region_id>\d+)/$', 'member_requests'),
    (r'^member-requests/to-be-confirmed/$', 'member_requests', {'status': '6'}),
    (r'^member-requests/twa-ids/$', 'create_twa_ids'),
    (r'^member-requests/rejected/$', 'member_requests', {'status': '3'}),
    (r'^member-requests/verify/$', 'member_requests', {'status': '4'}),
    (r'^member-requests/xls/$', 'membership_requests_xls'),
    (r'^member/(\d+)/$', 'member'),
    (r'^members/$', 'members'),
    (r'^members/all/$', 'members_all'),
    (r'^members/csv/$', 'members_csv'),
    (r'^members/xls/$', 'members_xls'),
    (r'^news/$', 'news'),
    (r'^news/(?P<news_id>\d+)/$', 'news'),
    (r'^news/preview/(\d+)/$', 'news_preview'),
    (r'^news/year/(?P<year>\d+)/$', 'news'),
    (r'^nominations-xls$', 'nominations_xls'),
    (r'^region/(\d+)/csv/$', 'region_csv'),
    (r'^seminar/(?P<seminar_id>\d+)/$', 'seminar'),
    (r'^seminars/$', 'seminar'),
    (r'^seminars/year/(?P<year>\d+)/$', 'seminar'),
    (r'^suggestions/$', 'suggestions'),
    (r'^twa-region/$', 'twa_region'),
    (r'^twa-region/region/(?P<region_id>\d+)/$', 'twa_region'),
    (r'^(?P<path>.*)$', 'dynamic_pages'),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
        )

members/models.py
#-*- coding: utf-8 -*-

import calendar
from datetime import date
from datetime import datetime

from PIL import Image
from django.conf import settings
from django.contrib.flatpages.models import FlatPage
from django.contrib.syndication.views import Feed
from django.core.exceptions import MultipleObjectsReturned
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.db.models import Q
from django.forms import ValidationError
from django.utils import translation
from django.utils.feedgenerator import Atom1Feed
from django.utils.translation import ugettext_lazy as _

from twa.members import helpers
from twa.members.helpers import MARKUP_MARKDOWN, MARKUP_REST, MARKUP_TEXTILE, MARKUP_TEXT, txt_to_html
from twa.settings import DOCUMENTS_DIR
from twa.utils import AbstractModel
from twa.utils import DEFAULT_MAX_LENGTH

doc_file_system = FileSystemStorage(location=DOCUMENTS_DIR)

GENDER = [
    ('m', _('male')),
    ('f', _('female')),
]

TWA_REGION = [
    (1, 'Eckhardt'),
    (2, 'Peter'),
    (3, 'Volker'),
    (4, 'Robert/Stephan'),
    (5, 'Milan'),
    (6, 'Tendokan'),
    (7, 'Ludo'),
    (8, 'Tim'),
]

NAME_PREFIX = [
    ('d', _('Dr.')),
    ('p', _('Prof.')),
    ('dd', _('Dr. Dr.')),
    ('pd', _('Prof. Dr.')),
]

RANK = [
    (1000, _('10. Dan')),
    (900, _('9. Dan')),
    (800, _('8. Dan')),
    (700, _('7. Dan')),
    (600, _('6. Dan')),
    (500, _('5. Dan')),
    (400, _('4. Dan')),
    (300, _('3. Dan')),
    (200, _('2. Dan')),
    (100, _('1. Dan')),
    (50, _('1. Kyu')),
    (40, _('2. Kyu')),
    (30, _('3. Kyu')),
    (20, _('4. Kyu')),
    (10, _('5. Kyu')),
    (9, _('6. Kyu')),
]

LICENSE_STATUS_OPEN = 1
LICENSE_STATUS_ACCEPTED = 2
LICENSE_STATUS_REJECTED = 3
LICENSE_STATUS_VERIFY = 4
LICENSE_STATUS_LICENSED = 5
LICENSE_STATUS_NOT_RENEWED = 6

LICENSE_STATUS = [
    (LICENSE_STATUS_OPEN, _('open')),
    (LICENSE_STATUS_ACCEPTED, _('accepted')),
    (LICENSE_STATUS_REJECTED, _('rejected')),
    (LICENSE_STATUS_VERIFY, _('verify')),
    (LICENSE_STATUS_LICENSED, _('licensed')),
    (LICENSE_STATUS_NOT_RENEWED, _('not renewed')),
]

MEMBERSHIP_STATUS_OPEN = 1
MEMBERSHIP_STATUS_ACCEPTED = 2
MEMBERSHIP_STATUS_REJECTED = 3
MEMBERSHIP_STATUS_VERIFY = 4
MEMBERSHIP_STATUS_CONFIRMED = 5
MEMBERSHIP_STATUS_TO_BE_CONFIRMED = 6
MEMBERSHIP_STATUS_MEMBER = 10
MEMBERSHIP_STATUS_EX = -1

MEMBERSHIP_STATUS = [
    (MEMBERSHIP_STATUS_OPEN, _('open')),
    (MEMBERSHIP_STATUS_ACCEPTED, _('accepted')),
    (MEMBERSHIP_STATUS_CONFIRMED, _('confirmed')),
    (MEMBERSHIP_STATUS_TO_BE_CONFIRMED, _('to be confirmed')),
    (MEMBERSHIP_STATUS_REJECTED, _('rejected')),
    (MEMBERSHIP_STATUS_VERIFY, _('verify')),
    (MEMBERSHIP_STATUS_MEMBER, _('member')),
    (MEMBERSHIP_STATUS_EX, _('exit')),
]

MARKUP_CHOICES = (
    (MARKUP_MARKDOWN, MARKUP_MARKDOWN),
    (MARKUP_REST, MARKUP_REST),
    (MARKUP_TEXTILE, MARKUP_TEXTILE),
    (MARKUP_TEXT, MARKUP_TEXT),
)

__textile_url = 'http://en.wikipedia.org/wiki/Textile_%28markup_language%29'
__rest_url = 'http://docutils.sourceforge.net/docs/user/rst/quickref.html'
__markdown_url = 'http://daringfireball.net/projects/markdown/syntax'
MARKUP_HELP = 'Text formatting. Default is plain text. For other formats see documentation: <a href="%s" target="_blank">Markdown</a>, <a href="%s" target="_blank">reStructuredText</a>, <a href="%s" target="_blank">textile</a>' % (__markdown_url, __rest_url, __textile_url)


def validate_not_before(value, before=date(1900, 1, 1)):
    """Raises a `ValidationError` if a date is before the specified limit."""
    if value < before:
        raise ValidationError(_('"%(value)s" is not a valid date. (Date may not be before %(before)s.)') % dict(value=value, before=before))


def validate_not_before_dt(value, before=datetime(1900, 1, 1)):
    """Raises a `ValidationError` if a datetime is before the specified limit."""
    if value < before:
        raise ValidationError(_('"%(value)s" is not a valid date. (Date may not be before %(before)s.)') % dict(value=value, before=before))


def validate_no_future(value):
    """Raises a `ValidationError` if a date is in the future."""
    if value > date.today():
        raise ValidationError(_('"%(value)s" is not a valid date. (Date may not be in the future.)') % dict(value=value))


def validate_no_future_dt(value):
    """Raises a `ValidationError` if a datetime is in the future."""
    if value > datetime.utcnow():
        raise ValidationError(_('"%(value)s" is not a valid date. (Date may not be in the future.)') % dict(value=value))


class Country(AbstractModel):
    name = models.CharField(_('Name (en)'), max_length=DEFAULT_MAX_LENGTH, unique=True)
    code = models.CharField(_('Code'), max_length=2, unique=True)
    name_de = models.CharField(_('Name (de)'), max_length=DEFAULT_MAX_LENGTH, blank=True)
    name_ja = models.CharField(_('Name (ja)'), max_length=DEFAULT_MAX_LENGTH, blank=True)

    def get_name(self, language=None):
        return getattr(self, "name_%s" % (language or translation.get_language()[:2]), "") or self.name

    def __unicode__(self):
        return self.get_name()

    class Meta:
        ordering = ['name']
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')


class AllPersonsManager(models.Manager):
    use_for_related_fields = True

    def get_query_set(self):
        SQL_GRAD = "SELECT MAX(rank) FROM members_graduation WHERE members_graduation.is_nomination = false AND members_graduation.person_id=members_person.id"
        # SQL_GRAD_DATUM = "SELECT date FROM members_graduation WHERE members_graduation.person_id=members_person.id AND rank=(%s)" % SQL_GRAD
        return super(AllPersonsManager, self).get_query_set().extra(select={'crank': SQL_GRAD})


class PersonManager(AllPersonsManager):
    def get_query_set(self):
        return super(PersonManager, self).get_query_set().filter(is_active=True, public=True)

    def get_persons_by_rank(self, rank):
        return self.get_query_set().filter(crank=rank)

    def get_licensed(self):
        return self.get_query_set().filter(license__status=LICENSE_STATUS_LICENSED)

    def get_by_requested_licenses(self):
        return self.get_query_set().filter(license__request__isnull=False, license__date__isnull=True)

    def get_by_requested_membership(self):
        return self.get_query_set().filter(twamembership__request__isnull=False, twamembership__date__isnull=True)

    def get_members(self):
        return self.get_query_set().filter(twamembership__status=MEMBERSHIP_STATUS_MEMBER)

    def get_next_birthdays(self):
        liste = []
        persons = self.get_query_set().filter(birth__isnull=False)
        for person in persons:
            if person.days() < 3:
                liste.append(person)
        liste.sort()
        return liste


class Person(AbstractModel):
    firstname = models.CharField(_('First Name'), max_length=DEFAULT_MAX_LENGTH)
    lastname = models.CharField(_('Last Name'), max_length=DEFAULT_MAX_LENGTH)
    nickname = models.CharField(_('Nickname'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    firstname_jp = models.CharField(_('Japanese First Name'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    lastname_jp = models.CharField(_('Japanese Last Name'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    name_prefix = models.CharField(_('Name Prefix'), max_length=5, choices=NAME_PREFIX, blank=True, null=True)
    text = models.TextField(_('Text'), blank=True, null=True)
    text_beirat = models.TextField(_('Text (Beirat)'), editable=False, blank=True, null=True)
    photo = models.ImageField(_('Photo'), storage=doc_file_system, upload_to='photos/', null=True, blank=True,
        help_text=_('This is used in non public sites, visible for logged in members only.'))
    public_photo = models.ImageField(_('Public Photo'), upload_to='images/', null=True, blank=True,
        help_text=_('This is used in public sites, for example seminar announcements.'))

    street = models.CharField(_('Street'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    zip = models.CharField(_('Zip'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    city = models.CharField(_('City'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    country = models.ForeignKey(Country, verbose_name=_('Country'))

    phone = models.CharField(_('Phone'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    fax = models.CharField(_('Fax'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    mobile = models.CharField(_('Mobile'), max_length=DEFAULT_MAX_LENGTH, blank=True, null=True)
    email = models.EmailField(_('Email'), blank=True, null=True)
    website = models.URLField(_('Website'), verify_exists=False, blank=True, null=True)

    birth = models.DateField(_('Birth'), blank=True, null=True, validators=[validate_not_before, validate_no_future])
    birth_sort_string = models.CharField(max_length=4, editable=False, null=True)
    gender = models.CharField(_('Gender'), max_length=1, choices=GENDER)

    is_active = models.BooleanField(_('Active'), default=True)
    aikido_since = models.DateField(_('Aikido'), blank=True, null=True, validators=[validate_not_before, validate_no_future])
    dojos = models.ManyToManyField('Dojo', verbose_name=_('Dojos'), blank=True, null=True)

    objects = AllPersonsManager()
    persons = PersonManager()

    def get_name(self, language=None):
        lang = language or translation.get_language()[:2]
        name = u''
        if self.name_prefix:
            name = self.get_name_prefix_display()
        if lang == 'ja':
            if self.lastname_jp:
                name += ' %s' % self.lastname_jp
            if self.firstname_jp:
                name += ' %s' % self.firstname_jp
        if self.firstname:
            name += ' %s' % self.firstname
        if self.nickname:
            name += ' "%s"' % self.nickname
        if self.lastname:

templates/2011/birthdays.html
{% extends "2011/index.html" %}
{% load i18n %}

{% block content %}
    <div>
        <div class="section-header">{% trans "Upcoming birthdays" %}:</div>
        <div class="section-meta"></div>
        <table>
        {% for person in birthdays %}
            <tr class="columnhover border">
                <td class="meta">
                    {% if person.days == 0 %}
                        <span class="edit">{% trans "today" %}</span>
                    {% else %}
                        {% if person.days == 1 %}
                            {% trans "tomorrow" %}
                        {% else %}
                            {{ person.days }} {% trans "Days" %}
                        {% endif %}
                    {% endif %}
                </td>
                <td>
                    <a href="{{ person.get_absolute_url }}">{{ person }}</a>
                </td>
                <td><span class="small">{% trans "turning" %}</span> {% ifequal person.days 0 %}{{ person.age }}{% else %}{{ person.age|add:"1" }}{% endifequal %}</td>
                <td>{{ person.birth|date:"Y-m-d" }}</td>
                <td>{% for dojo in person.dojos.all %}{{ dojo }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock %}

templates/2011/graduations.html
{% extends "2011/index.html" %}
{% load i18n %}
{% load l10n %}
{% load twa_tags %}

{% block content %}
    <div class="section-header">
        {% trans "Graduations" %} {% now "Y" %} <span class="small meta">({{ counter|localize }})</span>
    </div>

    <div class="section-meta">
        <div class="bottom-space">
            {% if perms.members.add_graduation %}
                <a href="/admin/members/graduation/add/" class="new">{% trans "new" %}</a>
            {% endif %}
        </div>
    </div>


<table width="100%">
  <tr>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Dojo" %}</th>
    <th>{% trans "Rank" %}</th>
    <th>{% trans "Date" %}</th>
  </tr>

{% for graduation in object_list %}
  <tr class="columnhover border {% cycle 'row1' 'row2' %}">
    <td class="dojo top"><a href="{{ graduation.person.get_absolute_url }}">{{ graduation.person }}</a></td>
    <td class="top">
        {% for dojo in graduation.person.dojos.all %}
            <div><a href="{{ dojo.get_absolute_url }}">{{ dojo }}</a></div>
        {% endfor %}
    </td>
    <td class="top">{{ graduation }}</td>
    <td class="top">{{ graduation.date|date:"Y-m-d"|default:"" }}</td>
  </tr>
{% endfor %}

{% if object_list|length_is:"0" %}
  <tr>
    <td class="meta" colspan="6">
      {% trans "None" %}
    </td>
  </tr>
{% endif %}
</table>


{% if is_paginated %}
<div class="white" align="center">
  <small>{% paginator %}</small>
</div>
{% endif %}

{% endblock %}

templates/2011/members.html
{% extends "2011/index.html" %}

{% load i18n %}
{% load l10n %}
{% load twa_tags %}

{% block content %}

    <div class="section-header">
        {% trans "Members" %} <span class="small meta">({{ counter|localize }})</span>
    </div>

    <div class="section-meta">
        {% if perms.members.add_person %}
            <a href="/admin/members/person/add/" class="edit">{% trans "new" %}</a>
        {% endif %}
    </div>

    <table class="person-table" width="100%">
        {% for person in object_list %}
            <tr class="columnhover border">

                <!-- NAME, DOJO -->

                <td class="top">
                    <a href="{{ person.get_absolute_url }}" class="name">{{ person }}</a>
                    {% if person.current_rank %}
                        <span class="small">{{ person.current_rank }}</span>
                    {% endif %}
                    <ul class="small">
                        {% for dojo in person.dojos.all %}
                            <li><a href="{{ dojo.get_absolute_url }}">{{ dojo.country.code }} - {{ dojo }}</a></li>
                        {% endfor %}
                    </ul>
                </td>

                <!-- TWA STATUS -->

                <td class="top">
                </td>

                <!-- TWA ID -->

                <td class="top">
                    {% for membership in person.twamembership_set.all  %}
                        <div>
                            {{ membership.twa_id }}
                        </div>
                        <div class="small">
                            <span class="status-{{ membership.status }}">&nbsp;&nbsp;</span>
                            <span>{{ membership.get_status_display }}</span>
                        </div>
                    {% endfor %}
                </td>

                <!-- TWA LICENSE -->

                <td class="top">
                    <div class="{% if not person.is_licensed and not person.is_license_requested %}meta{% endif %}">
                        {% trans "License" %}:
                        <div class="small">
                            {% if person.is_licensed %}
                                {% for license in person.license_set.all %}
                                    {{ license.date|date:"Y-m-d" }}
                                {% endfor %}
                            {% else %}
                                {% if person.is_license_requested %}
                                    {% trans "Requested" %}
                                {% else %}
                                    -
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </td>

                <!-- PHOTO -->

                <td class="top">
                    {% if person.photo %}
                        <a href="{{ person.get_absolute_url }}"><img
                              src="/image/{{ person.photo.name }}/64x64/"
                              class="photo"
                              align="right"
                              alt="[{{ person.firstname }} {{ person.lastname }}]"
                              title="{{ person.firstname }} {{ person.lastname }}"
                              /></a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    {% if is_paginated %}
    <div class="white" align="center">
        <small>{% paginator %}</small>
    </div>
    {% endif %}

    {% if user.is_superuser %}
        <div class="white" align="center">
            <small>
                <br/>{% trans "Export to" %} <a href="/members/xls/">xls</a>, <a href="/members/csv/">csv</a>
            </small>
        </div>
    {% endif %}

{% endblock %}

templates/2011/teachers-mailinglist.html
{% extends "2011/index.html" %}
{% load i18n %}
{% load twa_tags %}

{% block content %}
<div class="section-header">
    {{ _('Licensed Teachers Mailinglist') }}
</div>

<div class="section-meta">
    {{ object_list|length }} {% trans 'licensed teachers' %}
</div>

<div>
    <div>
        <a href='mailto:{% for license in object_list %}{{ license.person.email }}{% if not forloop.last %}, {% endif %}{% endfor %}'>{% trans 'Email to all licensed  teachers' %}</a>
        <span class="small news-meta">({{ object_list|length }})</span>
    </div>

    <div>&nbsp;</div>

    {% regroup object_list by person.dojos.all.0.country as license_list %}

    {% for country in license_list %}
        <div class="news-header">
            {{ country.grouper.code }} - {{ country.grouper.get_name }}
        </div>

        <div class="news-meta">
            <a href='mailto:{% for license in country.list %}{{ license.person.email }}{% if not forloop.last %}, {% endif %}{% endfor %}'>{% blocktrans with country=country.grouper.get_name%}Email to licensed teachers in {{ country }}{% endblocktrans %}</a>
            <span class="small news-meta">({{ country.list|length }})</span>
        </div>

        <div class="news-content overview">
        {% for license in country.list %}
            {% with person=license.person %}
                <div>
                    <a href="mailto:{{ person.email }}">{{ person.get_name }}</a>
                    {% if perms.members.change_person %}<a href="/admin/members/person/{{ person.id }}/" class="edit">{% trans "edit" %}</a>{% endif %}
                </div>
            {% endwith %}
        {% endfor %}
        </div>

        <div class="news-footer">
        </div>
    {% endfor %}
</div>
{% endblock %}